// Generated by https://quicktype.io

export interface CategoriesAdminResponse {
    isSuccess: boolean;
    message:   string;
    data:      CategoriesAdminDetails[];
}

export interface CategoriesAdminDetails {
    id:             number;
    categoryName:   string;
    categoryNameAr: string;
    description:    string;
    descriptionAr:  string;
    image:          string;
}
