// Generated by https://quicktype.io

export interface PlantAdminResponse{
    isSuccess: boolean;
    message:   string;
    data:      PlantAdminDetails[];
}

export interface PlantAdminDetails {
    plantId:                 number;
    plantNameEn:             string;
    plantNameAr:             string;
    plantDescriptionEn:      string;
    descriptionAr:           string;
    plantSeasonEn:           string;
    plantSeasonAr:           string;
    plantCareDetailsEn:      string;
    plantCareDetailsAr:      string;
    plantMedicalBenefiEntEn: string;
    plantMedicalBenefiEntAr: string;
    plantCategoryEn:         string;
    plantCategoryAr:         string;
    plantImage:              string;
}
